version: '3.8'

services:
  backend:
    build:
      context: ./avanzai-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./avanzai-backend:/app
    restart: always

  frontend:
    build:
      context: ./avanzai-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./avanzai-frontend:/app
    restart: always
    depends_on:
      - backend
